version: "2.1"
services: 
  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    labels:
      com.example.description: "mysql"
    ports:
      - "3306:3306"
    networks:
      develop-code:
        aliases: 
          - mysql
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    env_file: gogs_mysql.conf
    volumes:
      - "/opt/mysql/conf:/etc/mysql/conf.d"
      - "/opt/mysql/logs:/logs"
      - "/opt/mysql/data:/var/lib/mysql"
      - "/opt/mysql/outer:/outer"
    stdin_open: true
    tty: true
  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /opt/docker/gogs/:/data
    depends_on:
      - mysql
    networks:
      develop-code:
        aliases:
          - gogs
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.229-centos
    ports:
      - "10081:8080"
      - "50000:50000"
    volumes:
      - home:/var/jenkins_home
      - ./hosts:/etc/hosts
    networks:
      develop-code:
        aliases:
          - jenkins
    environment:
      JAVA_OPTS: -Dhudson.footerURL=http://www.liuxiaoyi.com.cn
    privileged: true
networks:
  develop-code:
volumes:
  home:
        

