version: "2.1"
services: 
  nginx:
    container_name: nginx
    image: nginx
    hostname: nginx
    privileged: true
    labels:
      com.example.description: "nginx"
    ports:
      - "80:80"
    networks:
      tcdh:
        aliases: 
          - updates.jenkins-ci.org
    volumes:
      - "/opt/nginx/www:/usr/share/nginx/html"
      - "/opt/nginx/logs:/var/log/nginx"
      - "/opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
    stdin_open: true
    tty: true
networks:
  tcdh:
