version: "2.4"
services: 
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.2-community
    hostname: sonarqube
    privileged: true
    labels:
      com.example.description: "sonarqube"
    ports:
      - "9000:9000"
    networks:
      docker-compose_develop-code:
        aliases: 
          - sonarqube
    volumes:
      - "/opt/sonarqube/conf"
      - "/opt/sonarqube/data"
      - "/opt/sonarqube/logs"
      - "/opt/sonarqube/extensions"
    stdin_open: true
    tty: true
networks:
  docker-compose_develop-code:
    external: true
