version: "2.4"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.229-centos
    ports:
      - "10081:8080"
      - "50000:50000"
    volumes:
      - home:/var/jenkins_home
      - ./hosts:/etc/hosts
    networks:
      tcdh:
        aliases:
          - jenkins
    environment:
      JAVA_OPTS: -Dhudson.footerURL=http://ali2.liushiqi.top
    privileged: true
networks:
  tcdh:
volumes:
  home:
